spring:
  datasource:
    url: jdbc:h2:mem:blog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
        show_sql: true
        jdbc:
          batch_size: 1000
        order_updates: true
        order_inserts: true
    open-in-view: false

  cloud:
    openfeign:
      client:
        config:
          testBlogClient:
            connectTimeout: 1000
            readTimeout: 1000
      okhttp:
        enabled: true
      httpclient:
        max-connections-per-route: 50

springdoc:
  swagger-ui:
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**

logging:
  level:
    com.example.blogapi: DEBUG
    org.hibernate.SQL: debug
    reactor.netty.http.client: DEBUG

management:
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true


resilience4j.circuitbreaker:
  circuit-breaker-aspect-order: 1
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 10
      permittedNumberOfCallsInHalfOpenState: 2
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      slowCallDurationThreshold: 5000ms
      recordExceptions:
        - feign.RetryableException
  instances:
    kakaoCircuitBreaker:
      baseConfig: default
    naverCircuitBreaker:
      baseConfig: default

resilience4j.retry:
  retry-aspect-order: 2
  configs:
    default:
      maxAttempts: 3
      waitDuration: 1000
      retryExceptions:
        - feign.RetryableException
  instances:
    kakaoCircuitBreaker:
      baseConfig: default
    naverCircuitBreaker:
      baseConfig: default

blog:
  api:
    kakao:
      base-url: https://dapi.kakao.com
      path: /v2/search/blog
    naver:
      base-url: https://openapi.naver.com
      path: /v1/search/blog.json

client:
  kakao:
    rest-api-key: KakaoAK 5c5832542f35560030096142dcd145d7
  naver:
    client-id: 5hXktxfnzYdbhhJciAkb
    client-secret: 9Xs_0_fmeu